const client = [
  {
    id: 1,
    
    numeClient: "Alex Enache",
    codClient: "Cl1",
    emailClient: "alex.enache@email.com",
    nrTelefon: "+40 712 345 678",

    notificari: [
      {
        icon:"confirmari",
        nume:"Rezervarea ta a fost confirmata",
        text:"Rezervarea la Water Villa Resort (id:SC-1248) a fost confirmata.",
        primita:"5 minute",
        check: false
      },
      {
        icon:"checkin",
        nume:"Check-in-ul se apropie",
        text:"Check-in pentru Beach parad resort este peste 2 zile.",
        primita:"1 ora",
        check: false
      },
      {
        icon:"oferte",
        nume:"Oferta speciala pentru tine",
        text:"Ai 15% reducere la urmatoarea ta rezervare. Foloseste condul stay15 pana pe 31 mai!",
        primita:" 3 ore",
        check: false
      },
      {
        icon:"reduceri",
        nume:"Reducere speciala",
        text:"Este disponibila o reducere la camera 3 din hotelul 1.",
        primita:"1 zi",
        check: true
      },
      {
        icon:"noutati",
        nume:"Politica de confidentialitate actualizata",
        text:"Am actualizat politica noastra de confidentialitate.",
        primita:"2 zile",
        check: true
      },
    ],

    rezervare:[
      {
        codRezervare: "SC-1248",
        locatiRez: "Male, Maldiv",
        recenzieCam: 5,
        rezervareFacuta: "15 mai 2024",
        cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
        pretTotal: "405 RON",
        pretTotalNr: 405,
        periadaCazare: "3 nopti",
        nrPerioada:3,
        pretNoapte:135,
        status: "Confirmata",
      },
      {
        codRezervare: "SC-12458",
        cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
        recenzieCam: 4,
        rezervareFacuta: "15 mai 2024",
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
        pretTotal: "405 RON",
        pretTotalNr: 405,
        periadaCazare: "3 nopti",
        nrPerioada:3,
        pretNoapte:135,
        status: "Anulata",
      },
      {
        codRezervare: "SC-12438",
        cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
        recenzieCam: 4.6,
        rezervareFacuta: "15 mai 2024",
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
        pretTotal: "405 RON",
        pretTotalNr: 405,
        periadaCazare: "3 nopti",
        nrPerioada:3,
        pretNoapte:135,
        status: "Finalizata",
      },
      {
        codRezervare: "SC-124138",
        cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
        recenzieCam: 3.9,
        rezervareFacuta: "15 mai 2024",
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
        pretTotal: "405 RON",
        pretTotalNr: 405,
        periadaCazare: "3 nopti",
        nrPerioada:3,
        pretNoapte:135,
        status: "In desfasurare",
      },
      {
        codRezervare: "SC-124148",
        cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
        recenzieCam: 4.4,
        rezervareFacuta: "15 mai 2024",
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
        pretTotal: "405 RON",
        pretTotalNr: 405,
        periadaCazare: "3 nopti",
        nrPerioada:3,
        pretNoapte:135,
        status: "Confirmata",
      },
      {
        codRezervare: "SC-1241618",
        cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
        recenzieCam: 5,
        rezervareFacuta: "15 mai 2024",
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
        pretTotal: "405 RON",
        pretTotalNr: 405,
        periadaCazare: "3 nopti",
        nrPerioada:3,
        pretNoapte:135,
        status: "Anulata",
      },
      {
        codRezervare: "SC-124008",
        recenzieCam: 4.7,
        rezervareFacuta: "15 mai 2024",
        cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
        pretTotal: "405 RON",
        pretTotalNr: 405,
        periadaCazare: "3 nopti",
        nrPerioada:3,
        pretNoapte:135,
        status: "Finalizata",
      },
    ]
  },
]

export default client;