const clienti = [
  {
    id: 1,
    pozaProfil: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
    nume: "Maria Popa",
    codClient: "Cl1",
    email: "maria.popa@email.com",
    nrTelefon: "+40 714 531 678",
    tara:"Romania",
    nrTotalRezervari: 5,
    nrTotalIncasari: 5240,
    rezervari: [
      {
        id: 1,
        data: "10 mai 2023",
        pretRez: 400,
        codCamer: "C1",
        status: "Finalizata",
        codRezervare: "SC-1248",
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        codRezervare: "SC-1248",
        periadaCazare:3,
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
      },
      {
        id: 2,
        data: "30 iunie 2026",
        pretRez: 144,
        status: "Anulata",
        codCamer: "C3",
        codRezervare: "SC-1249",
        numeHotel: "Water ede",
        numeCamera: "Camera 2",
        checkIn: "19 iuni 2026",
        oraCheckIn: "15:00",
        checkOut: "23 august 2025",
        oraCheckOut: "11:00",
        codRezervare: "SC-1247",
        periadaCazare:3,
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
      }
    ]
  },

  {
    id: 2,
    pozaProfil: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
    nume: "Alexandru Ionescu",
    codClient: "Cl2",
    email: "alex.ionescu@email.com",
    nrTelefon: "+40 721 456 332",
    tara:"Romania",
    nrTotalRezervari: 3,
    nrTotalIncasari: 3890,
    rezervari: [
      {
        id: 1,
        data: "1 ianuarie 2025",
        pretRez: 54,
        codCamer: "C3",
        status: "Finalizata",
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 3",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        codRezervare: "SC-1246",
        periadaCazare:3,
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
      },
      {
        id: 2,
        data: "30 septembrie 2025",
        pretRez: 43,
        codCamer: "C4",
        status: "Finalizata",
        numeHotel: "Water vila cu piscina privata",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        codRezervare: "SC-1245",
        periadaCazare:3,
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
      }
    ]
  },

  {
    id: 3,
    pozaProfil: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
    nume:"Vlad Mihai",
    codClient: "Cl3",
    email: "vlad.mihai@email.com",
    nrTelefon: "+40 745 678 901",
    tara:"Germania",
    nrTotalRezervari:7,
    nrTotalIncasari: 7850,
    rezervari: [
      {
        id: 1,
        data: "10 mai 2025",
        pretRez: 534,
        codCamer: "C2",
        status: "Finalizata",
        numeHotel: "Water vila cu  ad",
        numeCamera: "Camera 1",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        codRezervare: "SC-1244",
        periadaCazare:3,
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
      },
      {
        id: 2,
        data: "24 februarie 2026",
        pretRez: 1341,
        codCamer: "C7",
        status: "Finalizata",
        numeHotel: "Water vila cu dprivata",
        numeCamera: "Camera 3",
        checkIn: "10 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        codRezervare: "SC-1243",
        periadaCazare:3,
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
      }
    ]
  },

  {
    id: 4,
    pozaProfil: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
    nume: "Ioana Dumitru",
    codClient: "Cl4",
    email: "ioana.dumitru@email.com",
    nrTelefon: "+40 721 111 333",
    tara:"Italia",
    nrTotalRezervari: 1,
    nrTotalIncasari: 1290,
    rezervari: [
      {
        id: 1,
        data: "1 martie 2026",
        pretRez: 144,
        codCamer: "C1",
        status: "Anulata",
        numeHotel: "Water asd privata",
        numeCamera: "Camera 4",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        codRezervare: "SC-1242",
        periadaCazare: 3,
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
      },
      {
        id: 2,
        data: "10 iunie 2026",
        codCamer: "C5",
        pretRez: 1443,
        status: "Anulata",
        numeHotel: "Water asd",
        numeCamera: "Camera 5",
        checkIn: "20 mai 2026",
        oraCheckIn: "15:00",
        checkOut: "23 mai 2026",
        oraCheckOut: "11:00",
        codRezervare: "SC-1241",
        periadaCazare:3,
        nrOaspetiAdulti: "2 adulti",
        nrOaspetiCopii: "0 copii",
      }
    ]
  },



]

export default clienti;