const rezervare = [
  {
    id: 1,
    codRezervare: "SC-1248",
    numeClient: "Maria Popa",
    codClient: "Cl1",
    emailClient: "mariapopa@email.com",
    nrTelefon: "+40 712 345 678",
    cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
    numeHotel: "Water vila cu piscina privata",
    numeCamera: "Camera 1",
    checkIn: "20 mai 2026",
    oraCheckIn: "15:00",
    checkOut: "23 mai 2026",
    oraCheckOut: "11:00",
    nrOaspetiAdulti: "2 adulti",
    nrOaspetiCopii: "0 copii",
    pretTotal: "405 RON",
    pretTotalNr: 405,
    periadaCazare: "3 nopti",
    nrPerioada:3,
    pretNoapte:135,
    status: "Confirmata",
    bgStatus: "bg-green-400/30",
    textStatus: "text-green-400"
  },
  {
    id: 2,
    codRezervare: "SC-1247",
    numeClient: "Ion Caramit",
    codClient: "Cl2",
    emailClient: "ioncaramit@email.com",
    nrTelefon: "+40 712 332 678",
    cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
    numeHotel: "Water vila ",
    numeCamera: "Camera 2",
    checkIn: "21 mai 2026",
    oraCheckIn: "12:00",
    checkOut: "25 mai 2026",
    oraCheckOut: "14:00",
    nrOaspetiAdulti: "3 adulti",
    nrOaspetiCopii: "1 copil",
    pretTotal: "4045 RON",
    pretTotalNr: 4045,
    pretNoapte:1011.25,
    periadaCazare: "4 nopti",
    nrPerioada:4,
    status: "In asteptare",
    bgStatus: "bg-orange-400/30",
    textStatus: "text-orange-400"
  },
  {
    id: 3,
    codRezervare: "SC-1246",
    numeClient: "Filimon Ioana",
    codClient: "Cl3",
    emailClient: "filiomioana@email.com",
    nrTelefon: "+40 712 332 120",
    cameraImg: `${import.meta.env.BASE_URL}home/descopera/exotic.jpg`,
    numeHotel: "Water vildsaa ",
    numeCamera: "Camera 3",
    checkIn: "1 mai 2026",
    oraCheckIn: "9:00",
    checkOut: "10 mai 2026",
    oraCheckOut: "18:00",
    nrOaspetiAdulti: "2 adulti",
    nrOaspetiCopii: "3 copil",
    pretTotal: "10000 RON",
    pretTopretTotalNrtal:10000,
    pretNoapte:111.11,
    periadaCazare: "9 nopti",
    nrPerioada:9,
    status: "Anulata",
    bgStatus: "bg-red-400/30",
    textStatus: "text-red-400"
  },
]

export default rezervare;